export const authConstants = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILIURE: "LOGIN_FAILIURE",
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    IS_USER_LOGGEDIN: 'IS_USER_LOGGEDIN'
}
