import React from 'react';
import './App.css';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import { Layout, Menu } from 'antd'; 

//IMPORTING PAGES:
import HomePage from './pages/HomePage';
import LoginPage from './pages/LoginPage';
import RegisterPage from './pages/RegisterPage';
import 'antd/dist/antd.css';

const { Header, Content, Footer } = Layout;

const App = ()=> {
  return (
    <>
     <Layout>
    <Header style={{ position: 'fixed', zIndex: 1, width: '100%' }}>
      <div className="logo" />
      <Menu
        theme="dark"
        mode="horizontal"
        defaultSelectedKeys={['2']}
        items={[{
          label: (
            <a href="/login">
              Login
            </a>
          ),
          key: 'login',
        },
        {
          label: (
            <a href="/register">
              Register
            </a>
          ),
          key: 'register',
        },
      ]}
      >
      </Menu>
    </Header>
    <Content className="site-layout" style={{ padding: '0 50px', marginTop: 64 }}>
      <div className="site-layout-background" style={{ padding: 24, minHeight: 380 }}>
      <Router>
      <main>
          <Routes>
          <Route path='/' element={<HomePage />}></Route>
          <Route path='/login' element={<LoginPage />}></Route>
          <Route path='/register' element={<RegisterPage />}></Route>
          </Routes>
      </main>
    </Router>
      </div>
    </Content>
    <Footer style={{ textAlign: 'center' }}>Generated by RootAID</Footer>
  </Layout>
    
    </>
  );

}

export default App;
