import React from 'react'

//IMPORTING MUI LIBS:
import { Box, Typography, AppBar, Toolbar} from '@mui/material'

const Footer = () => {
  return (
    <>
        <footer>
          <Box
          alignItems="center" 
          justifyContent={"center"}
          margin="auto"
          >
            <AppBar position='relative' color='default' style={{marginTop: '50px'}}>
            <Toolbar>
              <Typography 
              variant="caption" 
              component="div"
              justifyContent={"center"}>
                Template generated by RootAID
              </Typography>
            </Toolbar>
          </AppBar>
          </Box>
          
        </footer>
    </>
  )
}

export default Footer